apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "database.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "database.fullname" . }}-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "database.fullname" . }}-db
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "database.fullname" . }}-secret
              key: db_root_password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "database.fullname" . }}-pvc