apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 5000
  selector:
    app: {{ include "backend.fullname" . }}-api
  type: {{ .Values.service.type }}